apiVersion: v1
kind: Service
metadata:
  name: court-record-check-worker-dev-service
spec:
  selector:
    app: court-record-check-worker-dev-deployment
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80 
    targetPort: 8000
